name: "Packages Split"

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  # 1. for Github split
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          - local_path: "gatsby-plugin-gwpt-image"
            split_repository: "gatsby-plugin-gwpt-image"
          - local_path: "gatsby-plugin-gwpt-packages"
            split_repository: "gatsby-plugin-gwpt-packages"
          - local_path: "gatsby-plugin-gwpt-packages-light"
            split_repository: "gatsby-plugin-gwpt-packages-light"
          - local_path: "gatsby-plugin-gwpt-tailwind"
            split_repository: "gatsby-plugin-gwpt-tailwind"
          - local_path: "gatsby-plugin-gwpt-tailwind"
            split_repository: "gatsby-plugin-gwpt-tailwind-light"
          - local_path: "gatsby-plugin-gwpt-utils"
            split_repository: "gatsby-plugin-gwpt-utils"
          - local_path: "gatsby-plugin-wordpress-parser"
            split_repository: "gatsby-plugin-wordpress-parser"
          - local_path: "gatsby-plugin-wp-seo"
            split_repository: "gatsby-plugin-wp-seo"
          - local_path: "gatsby-plugin-wp-seo"
            split_repository: "gatsby-plugin-wp-seo-light"
          - local_path: "gatsby-plugin-wpcf7"
            split_repository: "gatsby-plugin-wpcf7"
          - local_path: "gatsby-theme-wp-search"
            split_repository: "gatsby-theme-wp-search"
          - local_path: "gatsby-theme-acf-builder"
            split_repository: "gatsby-theme-acf-builder"
          - local_path: "gatsby-theme-blog-data"
            split_repository: "gatsby-theme-blog-data"
          - local_path: "gatsby-theme-blog-data-light"
            split_repository: "gatsby-theme-blog-data-light"
          - local_path: "gatsby-theme-wp-comments"
            split_repository: "gatsby-theme-wp-comments"
          - local_path: "gatsby-theme-wp-data"
            split_repository: "gatsby-theme-wp-data"

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: "packages/${{ matrix.package.local_path }}"

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: "gatsbywpthemes"
          repository_name: "${{ matrix.package.split_repository }}"

          # ↓ the user signed under the split commit
          user_name: "gatsbywpthemes"
          user_email: "gatsbywpthemes@gmail.com"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: "packages/${{ matrix.package.local_path }}"

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: "gatsbywpthemes"
          repository_name: "${{ matrix.package.split_repository }}"

          # ↓ the user signed under the split commit
          user_name: "gatsbywpthemes"
          user_email: "gatsbywpthemes@gmail.com"
